import {Dimensions, StatusBar} from 'react-native';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const { width } = Dimensions.get('window');

export default {
  Maincontainer: {
    flex: 1,
    flexGrow: 1,
    width: windowWidth,
    marginTop: StatusBar.currentHeight || 0,
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    // borderWidth: 1,
    // borderColor: 'yellow'
  },
  image: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // width: windowWidth,
    // height:windowHeight,
  },
  TopDiv: {
    flex: 1,
    flexGrow: 5,
    // width: windowWidth,
    backgroundColor: '#0E3F6C',
    // borderColor: 'red',
    // borderWidth: 1,
  },
  TopInnerDivLogo: {
    flex: 1,
    flexGrow: 0.1,
    justifyContent: 'center',
    alignItems: 'center',
    // borderColor: 'pink',
    // borderWidth: 1,
    width: windowWidth,
  },
  InnerDivDots: {
    flex: 1,
    width: '100%',
    height: '100%',
    flexGrow: 0.7,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'red',
    flexDirection: 'row',
  },
  ImageLogoCss: {
    flex: 1,
    flexGrow: 1,
    width: '33.7%',
    resizeMode: 'stretch',
    // maxHeight:300,
    marginTop: 35,
    minHeight: 44,
  },
  TopInnerDivImgContainer: {
    flex: 1,
    flexGrow: 0.45,
    // borderColor: 'pink',
    // borderWidth: 1,
    width: windowWidth,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  ImageCss: {
    flex: 1,
    flexGrow: 1,
    width: '64%',
    resizeMode: 'stretch',
    maxHeight: 200,
  },
  TopInnerDivTextConatiner: {
    flex: 1,
    flexGrow: 0.45,
    // borderColor: 'pink',
    // borderWidth: 1,
    width: windowWidth,
  },
  TopInnerDivTextConatinerTitle: {
    flex: 1,
    flexGrow: 1,
    // borderColor: 'black',
    // borderWidth: 1,
    justifycontent: 'center',
    alignItems: 'center',
  },
  TitleDiv: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: 'red'
  },
  Title: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontFamily: 'Jost',
    fontSize: 17,
    letterSpacing: 0.4,
    padding: 2,
  },
  TopInnerDivTextConatinerContent: {
    flex: 1,
    flexGrow: 3,
    borderColor: 'black',
    // borderWidth: 1,
    // justifycontent: "center",
    alignItems: 'center',
  },
  ContentDiv: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: 'red',
    width: '93%',
  },
  Content: {
    color: '#F5F5F5',
    fontFamily: 'Jost',
    fontSize: 14.5,
    lineHeight: 24,
    width: '53%',
    textAlign: 'center',
  },
  TopInnerDivDots:{
      // flex:1,
      // flexGrow:0.025,
      // borderColor: 'pink',
      // borderWidth: 1,
      // width: windowWidth,
  },
  BottomDiv: {
    flex: 1,
    flexGrow: 2,
    // borderColor: 'green',
    // borderWidth: 1,
    padding: 2,
  },
  BottomDivTextContianer: {
    flex: 1,
    flexGrow: 0.7,
    justifycontent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: 'black',
    padding: 2,
  },
  BottomDivTextContianerLet: {
    flex: 1,
    flexGrow: 1,
    justifycontent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: 'black',
    paddingTop: 20,
    padding: 2,
  },
  BottomText: {
    color: '#707070',
    fontFamily: 'Jost',
    fontSize: 14.5,
    lineHeight: 24,
    fontWeight: 'bold',
    width: '100%',
    textAlign: 'center',
    padding: 2,
  },
  BottomDivInput: {
    flex: 1,
    flexGrow: 0.3,
    justifycontent: 'center',
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: 'pink',
    padding: 2,
  },
  BottomDivButtonInner: {
    flex: 1,
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    width: 300,
    borderWidth: 0.15,
    margin: 10,
    borderColor: 'black',
    maxHeight: 40,
    padding: 2,
    // borderRadius:4,
  },
  BottomDivButton: {
    flex: 1,
    flexGrow: 1,
    flexDirection: 'row',
    // borderWidth: 1,
    // borderColor: 'pink',
    padding: 2,
  },
  NineOne: {
    // padding:6,
    fontWeight: 'bold',
    paddingLeft: 10,
    alignSelf: 'center',
  },
  VerticleLine: {
    alignSelf: 'center',
    height: '80%',
    borderWidth: 0.2,
    borderColor: '#A2A2A2',
    marginLeft: 20,
  },
  EnterMo: {
    alignSelf: 'center',
    color: '#A2A2A2',
    marginLeft: 30,
  },
  InputContainer: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },

  // onboardin auto testing 
  container: { flex: 1, backgroundColor: 'white' },
  child: { width, justifyContent: 'center' },
  text: { fontSize: width * 0.5, textAlign: 'center' },
};
