let constants = {
    ACTIONS: {
      SAVE_PACKAGE_LIST: 'SAVE_PACKAGE_LIST',
      SAVE_SELECTED_PACKAGE: 'SAVE_SELECTED_PACKAGE',
      CLEAR_DATA: 'CLEAR_DATA',
      CLOSE_PACKAGE_MODAL: 'CLOSE_PACKAGE_MODAL',
      OPEN_PACKAGE_MODAL: 'OPEN_PACKAGE_MODAL',
      UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST',
      UPDATE_PACKAGE_LIST: 'UPDATE_PACKAGE_LIST',
      GET_MYCART:'GET_MYCART'
    },
    TEXTS: {
      }
  };
  export default constants;