const constants = {
    ACTIONS : {
        GET_COUPON:'GET_COUPON',
        SET_PRICE_OBJ:'SET_PRICE_OBJ',
        BOOKING_SUCCESS:'BOOKING_SUCCESS',
        PAYMENT_SUCCESS:'PAYMENT_SUCCESS',
        RAZORPAY_SUCESS: 'RAZORPAY_SUCESS',
        CLEAR_BOOKING_RESPONSE: 'CLEAR_BOOKING_RESPONSE'
    }
}
export default constants;