module.exports = {
  LOGIN: '/notification/send_otp/',
  LOGOUT: '',
  USER: '/auth/shortprofile/',
  RECEIVEOTP: '/notification/send_otp/',
  VERIFYOTP: '/auth/users/otplogin/',
  ALLPHLEBOLIST: '/panel/data/',
  SAMPLEHANDOVER: '/phlebo/sample_handover/',
  EDITSAMPLEHANDOVER: '/phlebo/sample_handover/1/',
  PACKAGES: '/package/crmdata/',
  CITY: '/core/cities/',
  EDITPROFILE: '/auth/users/',
  LEADGENRATION: '/lead/generate-lead-by-user/',
  BANNER: '/blog/banner/',
  CUSTOMERBOOKINGDETAILS: '/booking/customer_booking/',
  DOWNLOAD: '/booking/report_status/',
  PINCODE: '/phlebo/pincode/',
  MYCART: '/cart/',
  ADDRESS: '/address/',
  ADDADDRESS: '',
  COUPON: '/coupon/data/',
  ADDRESS: '/auth/address/',
  EDITADDRESS: '/auth/address/',
  BOOKING_SLOT_COLLECTION_DATE: '/booking/booking_slot_collection_date/',
  CREATE_BOOKING:'/booking/customer/create/',
  CART:'/cart/',
  PAYMENT:'/payment/order_payment/',
  PHLEBOLOC:'/booking/phlebo_loc/',
  PLAN_DETAIL:'/package/data_web/',
  PARAMETERS:'/package/pack-parameter/',
  RSIKAREA:'/package/tags/',
  UPLOAD_PRESCREPTION: '/booking/prescription_upload/',
  REDCASHDETAILS: '/coupon/redcashdetails/'
};
