import * as React from 'react';

export const navigationRef = React.createRef();

export function navigate(name, param) {
  navigationRef.current?.navigate(name, {customParam: param});
}

export function resetScreen(screenName) {
  navigationRef.current?.reset({
    index: 0,
    routes: [{name: screenName}],
  });
}

export const Screens = {
  PENDING_SCREEN: 'PENDING_SCREEN',
  ONBOARD_SCREEN: 'ONBOARD_SCREEN',
  MYACCOUNT_SCREEN: 'MYACCOUNT_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  OTP_VERIFICATION: 'OTP_VERIFICATION',
  ALLPACKAGE: 'ALLPACKAGE',
  TABPACKAGES: 'TABPACKAGES',
  PLAN_DETAIL: 'PLAN_DETAIL',
  PROFILESCREEN: 'PROFILESCREEN',
  APPOINTMENT: 'APPOINTMENT',
  MAINSCREEN: 'MAINSCREEN',
  CITY: 'CITY',
  HELP: 'HELP',
  PATIENT_DETAILS: 'PATIENT_DETAILS',
  ADD_ADDRESS: 'ADD_ADDRESS',
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  ADD_SLOT: 'ADD_SLOT',
  ORDER_REVIEW: 'ORDER_REVIEW',
  MY_CART: 'MY_CART',
  MYFAMILY_FRIENDS: 'MYFAMILY_FRIENDS',
  BOOKING: 'BOOKING',
  PERSONAL_INFO: 'PERSONAL_INFO',
  EditPERSONAL_INFO: 'EditPERSONAL_INFO',
  MY_ORDER: 'MY_ORDER',
  MY_ADDRESS: 'MY_ADDRESS',
  USERADD_ADDRESS: 'USERADD_ADDRESS',
  EDIT_ADDRESS:'EDIT_ADDRESS',
  TERMS_CONDITION:'TERMS_CONDITION',
  TAB: 'TAB',
  EDITPROFILE: 'EDITPROFILE',
  SAMPLE_HANDOVER_SCREEN: 'SAMPLE_HANDOVER_SCREEN',
  TRACKING:'TRACKING',
  PHLEBODETAILS:'PHLEBODETAILS', 
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  UPLOAD_PRESCREPTION: 'UPLOAD_PRESCREPTION',
  PROFILE_ADDRESS :'PROFILE_ADDRESS',
  PROFILE_USER_ADDADDRESS : 'PROFILE_USER_ADDADDRESS',
  PROFILE_EDIT_ADDADDRESS : 'PROFILE_EDIT_ADDADDRESS',
  MY_REDCASH : 'MY_REDCASH',
};
