import {Dimensions, StatusBar} from 'react-native';

export default {
  // new style
  maindiv: {
    // backgroundColor: 'pink',
    minHeight: '100%',
  },
  topnav: {
    minHeight: 70,
    maxHeightL: 80,
    flexDirection: 'row',
    paddingLeft: '3%',
    paddingRight: '3%',
    paddingTop: '2%',
    paddingBottom: '2%',
    borderBottomColor: '#A2A2A2',
    borderWidth: 0.3,
    backgroundColor: 'white',
  },
  head: {
    flexGrow: 1,
    flex: 1,
    flexDirection: 'row',
    // backgroundColor: 'yellow',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    width: 120,
    height: 40,
    minHeight: 30,
    maxHeight: 40,
  },
  scrollsection: {
    // backgroundColor: 'green',
    flex: 1,
    paddingBottom: '35%',
  },
  searchsection: {
    minHeight: 90,
    maxHeight: 100,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchinputsection: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
    flexDirection: 'row',
    borderColor: '#A2A2A2',
    borderWidth: 0.2,
    borderRadius: 5,
    minWidth: '95%',
    maxWidth: '95%',
    minHeight: 40,
    maxHeight: 50,
    paddingLeft: 4,
    paddingRight: 4,
  },
  searchiconfield: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchicon: {
    fontSize: 25,
    color: '#E5184E',
    fontWeight: '500',
  },
  searchinputfield: {
    flex: 1,
    flexGrow: 6,
    justifyContent: 'center',
  },
  section: {
    flex: 1,
    marginTop:10,
    marginBottom:10,
    minHeight: 200,
    maxHeight: 250,
    // backgroundColor: 'blue',
    justifyContent: 'center',
    alignItems: 'center',
    // borderColor: 'red',
    // borderWidth: 1
  },
  rowsection: {
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 20,
    maxHeightL: 30,
  },
  press: {
    flex: 1,
    flexGrow: 1,
    flexDirection: 'row',
    width: '85%',
    justifyContent: 'space-between',
  },
  topic: {
    fontSize: 16,
    color: '#707070',
  },
  seeall: {
    fontSize: 14,
    color: '#E5184E',
  },
  card: {
    width: '90%',
    minHeight: 150,
    maxHeight: 200,
    backgroundColor: '#FFFFFF',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    flexGrow: 0.2,
    flexDirection: 'row',
    borderColor: '#A2A2A2',
    borderWidth: 0.2,
  },
  cardleft: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 170,
  },
  cardright: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
    paddingTop: '4%',
    paddingBottom: '4%',
  },
  cardimage: {
    width: 160,
    height: 130,
  },
  book: {
    fontSize: 14,
    color: '#FBFBFB',
    paddingVertical: '3%',
    paddingHorizontal: '10%',
    backgroundColor: '#E5184E',
    borderRadius: 5,
    maxWidth: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryrow: {
    flex: 1,
    flexGrow: 1,
    minHeight: 180,
    maxHeight: 190,
    flexDirection: 'row',
    // backgroundColor:'red',
    paddingLeft: 10,
    paddingRight: 10,
  },
  categoryicon: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 80,
    backgroundColor: '#FFFFFF',
    borderRadius: 5,
    shadowOffset: {width: 0, height: 5},
    shadowColor: '#313450',
    borderColor: '#A2A2A2',
    borderWidth: 0.2,
  },
  cardtextfield: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  touch: {
    flex: 1,
    flexGrow: 1,
    paddingTop: 15,
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 10,
  },
  resentrow: {
    marginTop: 10,
    flex: 1,
    flexGrow: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    // backgroundColor:'red',
    minWidth: '90%',
    maxWidth: '90%',
    paddingTop: '2%',
    paddingBottom: '3%',
  },
  resentcard: {
    flex: 1,
    flexGrow: 1,
    flexDirection: 'row',
    backgroundColor: 'white',
    // marginRight: '5%',
    borderRadius: 5,
    borderColor: '#A2A2A2',
    borderWidth: 0.2,
    minWidth: '35%',
    maxWidth: '49%',
    padding: 5,
  },
  row: {
    flex: 1,
    flexGrow: 1,
    flexDirection: 'row',
    width: '94%',
    justifyContent: 'space-between',
    paddingTop: '1%',
    paddingBottom: '1%',
  },
  bingbing: {
    fontWeight: 'bold',
    color: '#707070',
  },
  riskc: {
    color: '#A2A2A2',
    fontSize: 12,
  },
  cartNum: {
    top: 3,
    marginLeft:6, 
    backgroundColor: 'red',
    borderRadius: 10, 
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '700'
    },
    arrowAll : {
      flexDirection: 'row',
      alignItems: 'center'
    }
  // completeprofile: {
  //     backgroundColor: '#0E3F6C',
  //     paddingVertical: '2%',
  //     paddingHorizontal: '4%',
  //     borderRadius: 5,
  // },
  // package: {
  //     display: 'flex',
  //     justifyContent: 'center',
  //     alignItems: 'center',
  //     marginTop: '8%',
  //     height: '40%'
  // },
  // heading: {
  //     fontSize: 16,
  //     color: '#205072',
  // },
  // iconLogo:{
  //     height:200,
  //     width:300
  // }
};