let constants = {
    ACTIONS: {
      SAVE_BEST_PACKAGE_LIST: 'SAVE_BEST_PACKAGE_LIST',
      SAVE_SELECTED_PACKAGE: 'SAVE_SELECTED_PACKAGE',
      CLOSE_PACKAGE_MODAL: 'CLOSE_PACKAGE_MODAL',
      OPEN_PACKAGE_MODAL: 'OPEN_PACKAGE_MODAL',
      CLEAR_DATA: 'CLEAR_DATA',
      SAVE_MAIN_PACKAGE_LIST:'SAVE_MAIN_PACKAGE_LIST',
      SAVE_SELECTED_PACKAGE_LIST:'SAVE_SELECTED_PACKAGE_LIST',
      CLEAR_PACKAGES :'CLEAR_PACKAGES',
    },
    TEXTS: {
      }
  };
  export default constants;